language: generic

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "My-first-app"
  env: "My-first-app-env"

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket_name: "app-ki-bucket"

  bucket_path: "docker"

  on:
    branch: main